#!/bin/bash

# For automatic publishing in repo please put oAuth key in SynoBuildConf/GitHubOAuthToken.txt

echo Install requirements
npm install nan node-pre-gyp node-pre-gyp-github

export CC="${CC}"
export CXX="${CXX}"
export CFLAGS="${CFLAGS}"
export CXXFLAGS="${CXXFLAGS}"
export LDFLAGS="${LDFLAGS}"
export AR="${AR}"

echo "env after exports"
env

echo node_modules/.bin/node-pre-gyp --target_arch=arm configure
node_modules/.bin/node-pre-gyp --target_arch=arm configure


# echo adjust makefile
# echo "include /env32.mak" > build/Makefile.new
# cat build/Makefile >> build/Makefile.new
# mv build/Makefile build/Makefile.old
# mv build/Makefile.new build/Makefile


echo node_modules/.bin/node-pre-gyp --target_arch=arm build
node_modules/.bin/node-pre-gyp --target_arch=arm build


echo node_modules/.bin/node-pre-gyp --target_arch=arm package
node_modules/.bin/node-pre-gyp --target_arch=arm package


# publish release on github
TOKEN=`cat SynoBuildConf/GitHubOAuthToken.txt`
NODE_PRE_GYP_GITHUB_TOKEN="${TOKEN}" node_modules/.bin/node-pre-gyp-github publish
